spring:
  shardingsphere:
    datasource:
      database1:
        jdbc-url: jdbc:mysql://localhost:3306/database1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 100
          maximum-pool-size: 100
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: select 1
      database2:
        jdbc-url: jdbc:mysql://localhost:3306/database2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 100
          maximum-pool-size: 100
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: select 1
    sharding:
      tables:
        user:
          actual-data-nodes:  database2.user_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id%2}
              key-generator:
                column: id
                type: SNOWFLAKE
                props:
                  worker:
                    id: 123
                  sql:
                    show: true
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: database2
server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    max-connections: 10000