server:
  port: 8080
spring:
  application:
    name: testeverything
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
