spring:
  data:
    mongodb:
      customer:
        host: 10.70.0.17
        port: 27017
        database: saas_customer
        username: qingclass
        password: xCDMBKeKDJ#s
      course:
        host: 10.70.0.17
        port: 27017
        database: saas_course
        username: qingclass
        password: xCDMBKeKDJ#s
        authentication-database: admin
server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    max-connections: 10000