rocketmq:
  name-server: 192.168.133.131:9876
  producer:
    group: test-group
    send-message-timeout: 3000

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300